FROM centos:7

ADD CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo
ADD python3 /usr/local/python3

RUN \
	ln -s /usr/local/python3/bin/python3.8 /usr/bin/python3 && \
	ln -s /usr/local/python3/bin/pip3.8 /usr/bin/pip3
	