FROM centos:7

# 下载：http://mirrors.aliyun.com/repo/Centos-7.repo
COPY CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo
# 下载：https://www.python.org/ftp/python/3.8.1/Python-3.8.1.tgz
COPY Python-3.8.1.tgz Python-3.8.1.tgz

RUN \
	yum install -y zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make libffi-devel && \
	rpm -qa | grep python | xargs rpm -ev --allmatches --nodeps && \
	whereis python | xargs rm -frv && \
	# 安装python3
	tar -zxvf Python-3.8.1.tgz && \
	cd Python-3.8.1 && \
	./configure prefix=/usr/local/python3 && \
	make && make install && \
	ln -s /usr/local/python3/bin/python3.8 /usr/bin/python && \
	ln -s /usr/local/python3/bin/pip3.8 /usr/bin/pip && \
	pip install --upgrade pip && \
	rm -rf Python-3.8.1.tgz && \
	rm -rf Python-3.8.1

# 卸载
RUN \	
	rpm -qa|grep zlib-devel | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep bzip2-devel | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep openssl-devel | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep ncurses-devel | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep sqlite-devel | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep readline-devel | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep tk-devel | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep gcc | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep make | xargs rpm -ev --allmatches --nodeps && \
	rpm -qa|grep libffi-devel | xargs rpm -ev --allmatches --nodeps 
